### ISSUE TITLE
 __privateGet(...).defaultMutationOptions is not a function

### ISSUE THREAD

**Issue by poiuyt183** [medusajs/medusa#7114]
![image](https://github.com/medusajs/medusa/assets/81480245/6f06d120-6531-419f-8e96-873d33bbe4e8)
![image](https://github.com/medusajs/medusa/assets/81480245/03b45dd6-ae7f-46df-b9e9-fde643f84e0a)
![image](https://github.com/medusajs/medusa/assets/81480245/4755fcfa-5f36-416f-ae05-4a9fd7b3b319)

This error happen when I using useAdminLogin hook in my Login page. Help me, please!!

**Comment by poiuyt183** [comment]
This err occur and it does not render anything in my screen, only white screen

**Comment by kasperkristensen** [comment]
@hoshikira18 What version of `@tanstack/react-query` did you install? `medusa-react` only works with `<=4.22`, if you are using `>5` this error would occur as there are breaking changes that `medusa-react` is not compatible with.

**Comment by poiuyt183** [comment]
![image](https://github.com/medusajs/medusa/assets/81480245/cfab67a4-6971-4a82-86cf-1becfe8ca0ee)
I'm using react-query 4.22.4
