### ISSUE TITLE
Create medusa project failed at Run Migrations step

### ISSUE THREAD

**Issue by mervinyan** [medusajs/medusa#8332]
### An error occurred while preparing project: Error: An error occurred while running migrations: medusa migrations [action] [modules...]

I ran command `npx create-medusa-app@preview` in terminal however the project fails to be created due to error: An error occurred while preparing project: Error: An error occurred while running migrations: medusa migrations [action] [modules...]

![2024-07-29_08-08](https://github.com/user-attachments/assets/c46f6a7a-acd0-4ace-9ae2-b394c8a09aad)

### System information

Medusa version (including plugins): create-medusa-app@1.2.9-preview-20240727150435
Node.js version: v20.12.2
Database: postgresql 16
Operating system: ubuntu 22.04
Browser (if relevant): 

### Steps to reproduce the behavior

1. Go to terminal
2. Enter `npx create-medusa-app@preview`
3. Following the instructions to proceed
4. See error: `An error occurred while preparing project: Error: An error occurred while running migrations: medusa migrations [action] [modules...]`

### Expected behavior

All steps should be completed successfuly

### Screenshots

![2024-07-29_08-08](https://github.com/user-attachments/assets/c76e8f9c-3e0e-4ee4-8d4c-f48777dda712)

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

I checked the medusa database and found no tables

![2024-07-29_08-33](https://github.com/user-attachments/assets/efeab6eb-e16f-4021-b4e5-5dfa3e203e96)

**Comment by mervinyan** [comment]
Based on the source code of the `prepare-project.ts` looks like this failure was caused by the line `errorOccurred = migrations.rowCount == 0`...I aslo checked the newly created medusa database however found No tables at all...not sure what happened...

![image](https://github.com/user-attachments/assets/e211f3fc-5f5f-420e-8752-1f06c6300f3d)

**Comment by thetutlage** [comment]
@mervinyan 

Hey, did you try creating a new project in last couple of days? I suspect the issue might be related to some outdated dependencies. 

It will be nice if you can give it a try one more time and then let me know if the issue still persists. Also, can you ensure that before creating the app you have PostgreSQL running on your computer?

**Comment by mervinyan** [comment]
Hi @thetutlage,

I just tried few moments ago the issue still persists.
![image](https://github.com/user-attachments/assets/129625e7-51a4-4624-a32e-ddb4bc8443e4)

This time it failed at the `npm run build` command due to error `Cannot find module 'knex/lib/dialects/postgres/schema/pg-tablecompiler'`...see above screenshot

btw, I have the postgres running on my laptop and the medusa database has been created successfully by the create-medusa-app command
![image](https://github.com/user-attachments/assets/966cdb51-9842-47b0-b9f1-230bcd726ede)

**Comment by thetutlage** [comment]
Can you please share this project as a repo? I will try to reproduce the issue on my end

**Comment by mervinyan** [comment]
https://github.com/mervinyan/my-medusa-store

@thetutlage ^

Got error `Error: Cannot find module 'knex/lib/dialects/postgres/schema/pg-tablecompiler'` during  `yarn build` 
![image](https://github.com/user-attachments/assets/ade4b811-e244-43e9-8a69-65e997fc3ff3)

I am on Ubuntu 22.04...fyi

**Comment by thetutlage** [comment]
Hello @mervinyan 

I cloned the repo you shared and everything seems to be working fine for me. Here are some screenshots of the migrations and the build commands.

![CleanShot 2024-08-13 at 12 22 18@2x](https://github.com/user-attachments/assets/547d46f7-aa8a-4df7-8e0b-8deee71a642f)

![CleanShot 2024-08-13 at 12 22 10@2x](https://github.com/user-attachments/assets/56fbcec2-79a5-4a29-9910-8edfcafb2696)

I am using `yarn@4.4.0` and following is the contents of the `.env` file

```
MEDUSA_ADMIN_ONBOARDING_TYPE=default
STORE_CORS=http://localhost:8000,https://docs.medusajs.com
ADMIN_CORS=http://localhost:7000,http://localhost:7001,https://docs.medusajs.com
AUTH_CORS=http://localhost:7000,http://localhost:7001,https://docs.medusajs.com
REDIS_URL=redis://localhost:6379
JWT_SECRET=supersecret
COOKIE_SECRET=supersecret
DATABASE_URL=postgres://postgres@localhost/medusa-pjlk
POSTGRES_URL=postgres://postgres@localhost/medusa-pjlk
```

**Comment by mervinyan** [comment]
Hi @thetutlage ,

Thanks again for your help!

I figured it out... the curlprit was the yarn...I have v1.22 installed...after I upgraded it to v4 then the error is gone and I am able to run the migrations and build the project...

Thanks again and have a good day!

Mervin
