### ISSUE TITLE
Import Meta Build Errors

### ISSUE THREAD

**Issue by saranshisatgit** [medusajs/medusa#13059]
### Package.json file

```JSON
{
  "name": "jyt-commerce-api",
  "version": "6.0.1",
  "description": "A starter for Medusa projects extended to be used as a core production modules for textiles.",
  "author": "Medusa (https://medusajs.com) and JYT (https://jaalyantra.in)",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start",
    "dev": "medusa develop",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "predeploy": "medusa db:migrate",
    "generate-ui": "medusa exec ./src/scripts/generate-ui-v2.ts"
  },
  "dependencies": {
    "@ai-sdk/anthropic": "^1.1.17",
    "@ai-sdk/openai": "^1.3.0",
    "@ariakit/react": "^0.4.17",
    "@emoji-mart/data": "1.2.1",
    "@excalidraw/excalidraw": "^0.18.0",
    "@faker-js/faker": "^9.7.0",
    "@floating-ui/react": "^0.27.14",
    "@hookform/resolvers": "^5.0.1",
    "@mastra/core": "latest",
    "@mastra/loggers": "latest",
    "@medusajs/admin-sdk": "^2.8.8",
    "@medusajs/cli": "2.8.8",
    "@medusajs/framework": "2.8.8",
    "@medusajs/medusa": "2.8.8",
    "@medusajs/medusa-oas-cli": "^2.8.8",
    "@medusajs/workflows-sdk": "2.8.8",
    "@mikro-orm/core": "6.4.3",
    "@mikro-orm/knex": "6.4.3",
    "@mikro-orm/migrations": "6.4.3",
    "@mikro-orm/postgresql": "6.4.3",
    "@openrouter/ai-sdk-provider": "^1.0.0-beta.1",
    "@radix-ui/themes": "^3.2.1",
    "@tanstack/react-query-devtools": "^5.81.4",
    "@tiptap/pm": "^3.0.7",
    "@tiptap/react": "^3.0.7",
    "@types/leaflet": "^1.9.19",
    "@types/multer": "^1.4.12",
    "@types/react-color": "^3.0.13",
    "@types/react-json-editor-ajrm": "^2.5.6",
    "@uploadthing/react": "7.1.0",
    "@xyflow/react": "^12.4.4",
    "ai": "^4.3.9",
    "awilix": "^8.0.1",
    "class-variance-authority": "^0.7.1",
    "csv-parse": "^5.6.0",
    "date-fns": "^4.1.0",
    "framer-motion": "^12.4.3",
    "fzf": "0.5.2",
    "handlebars": "^4.7.8",
    "html2canvas-pro": "^1.5.8",
    "json-edit-react": "^1.27.2",
    "leaflet": "^1.9.4",
    "lowlight": "^3.3.0",
    "lucide-react": "^0.503.0",
    "pdf-lib": "^1.17.1",
    "pg": "^8.13.0",
    "react-color": "^2.19.3",
    "react-day-picker": "8.10.1",
    "react-dnd": "^16.0.1",
    "react-dnd-html5-backend": "^16.0.1",
    "react-hook-form": "^7.58.1",
    "react-hotkeys-hook": "^5.1.0",
    "react-json-editor-ajrm": "^2.5.14",
    "react-leaflet": "^4.2.1",
    "react-lite-youtube-embed": "^2.5.0",
    "react-player": "^2.16.0",
    "react-resizable-panels": "^2.1.8",
    "react-textarea-autosize": "^8.5.9",
    "react-tweet": "^3.2.2",
    "remark-math": "^6.0.0",
    "resend": "^4.7.0",
    "sonner": "^2.0.3",
    "twitter-api-sdk": "^1.2.1",
    "uploadthing": "7.2.0",
    "use-file-picker": "^2.1.2",
    "uuid": "^11.1.0",
    "zod": "^3.25.67",
    "@tiptap/extension-highlight": "^3.0.7",
    "@tiptap/extension-image": "^3.0.7",
    "@tiptap/extension-link": "^3.0.7",
    "@tiptap/extension-subscript": "^3.0.7",
    "@tiptap/extension-superscript": "^3.0.7",
    "@tiptap/extension-task-item": "^3.0.7",
    "@tiptap/extension-task-list": "^3.0.7",
    "@tiptap/extension-text-align": "^3.0.7",
    "@tiptap/extension-typography": "^3.0.7",
    "@tiptap/extension-underline": "^3.0.7",
    "@tiptap/starter-kit": "^3.0.7"
  },
  "devDependencies": {
    "@medusajs/test-utils": "2.8.8",
    "@mikro-orm/cli": "6.4.3",
    "@semantic-release/changelog": "^6.0.3",
    "@semantic-release/commit-analyzer": "^11.1.0",
    "@semantic-release/git": "^10.0.1",
    "@semantic-release/github": "^9.2.6",
    "@semantic-release/npm": "^11.0.2",
    "@semantic-release/release-notes-generator": "^12.1.0",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.13",
    "@types/lodash": "^4.17.13",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "jest-silent-reporter": "^0.6.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "sass": "^1.89.2",
    "sass-embedded": "^1.89.2",
    "semantic-release": "^23.0.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.8.3",
    "vite": "^5.2.11"
  },
  "engines": {
    "node": ">=20"
  },
  "packageManager": "yarn@1.22.22+sha512.a6b2f7906b721bba3d67d4aff083df04dad64c399707841b7acf00f6b133b7ac24255f2652fa22ae3534329dc6180534e98d17432037ff6fd140556e2bb3137e"
}
```

### Node.js version

v20.18.1

### Database and its version

17

### Operating system name and version

Mac OS Latest

### Browser name

Chromium

### What happended?

So, this build error started displaying after the upgrading to 2.8.8 

### Expected behavior

It should not throw this error since I have added vide-env.d.ts at the root of the admin src.

### Actual behavior

throwing src/admin/lib/config.ts:7:12 - error TS1470: The 'import.meta' meta-property is not allowed in files which will build into CommonJS output.

7   baseUrl: import.meta.env.VITE_MEDUSA_BACKEND_URL || "http://localhost:9000",
             ~~~~~~~~~~~
src/admin/lib/config.ts:7:24 - error TS2339: Property 'env' does not exist on type 'ImportMeta'.

7   baseUrl: import.meta.env.VITE_MEDUSA_BACKEND_URL || "http://localhost:9000",
                         ~~~
src/admin/lib/config.ts:8:10 - error TS1470: The 'import.meta' meta-property is not allowed in files which will build into CommonJS output.

8   debug: import.meta.env.DEV,
           ~~~~~~~~~~~
src/admin/lib/config.ts:8:22 - error TS2339: Property 'env' does not exist on type 'ImportMeta'.

8   debug: import.meta.env.DEV,
                       ~~~


### Link to reproduction repo

https://github.com/Jaal-Yantra-Textiles/v2

**Comment by Avia-Code** [comment]
@saranshisatgit could you share with us how you fixed it?
