### ISSUE TITLE
Extended repository example in document is not working

### ISSUE THREAD

**Issue by vinhnguyen1211** [medusajs/medusa#6139]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

I'm following this guide https://docs.medusajs.com/development/entities/extend-repository#step-2-implement-extended-repository
When I call http://localhost:9000/admin/products it keeps saying `productRepo.findWithRelationsAndCount is not a function`
![image](https://github.com/medusajs/medusa/assets/15612361/ae967b65-b350-437f-b7b2-c402fb0d3521)

### How can this issue be resolved?

I was able to fix the issue by proper deep copy 
```
export const OrderRepository = dataSource.getRepository(Order)
	.extend(Object.assign(MedusaOrderRepository, { target: Order }));
```

### Are you interested in working on this issue?

- [X] I would like to fix this issue

**Comment by shahednasser** [comment]
@adrien2p can I get you to confirm if this solution is correct?

**Comment by adrien2p** [comment]
@shahednasser @vinhnguyen1211 yes it seems that the documentation is missing the target replacement. it should be something like

```ts
export const ProductRepository = dataSource
  .getRepository(Product)
  .extend({
    // it is important to spread the existing repository here.
    //  Otherwise you will end up losing core properties
    ...Object.assign(MedusaProductRepository, { target: Product })

    /**
     * Here you can create your custom function
     * For example
     */
    customFunction(): void {
      // TODO add custom implementation
      return
    },
  })
```

**Comment by vinhnguyen1211** [comment]
@adrien2p @shahednasser spread operator doesn't work. I just test with your code snippet, it should be like this
```typescript
export const OrderRepository = dataSource.getRepository(Order).extend(
  Object.assign(MedusaOrderRepository, {
    customFunction(): void {
      // TODO add custom implementation
      return
    }
  }),
);
```
seems `{ target: Product }` is redundant

**Comment by adrien2p** [comment]
Spread operator works, I ve tested it myself, also, target is important if you are using a custom entity to replace the core one, otherwise if the core one is registered it will use the core entity. now if you don't have a custom entity it is not necessary.

<img width="1439" alt="Screenshot 2024-01-22 at 10 17 12" src="https://github.com/medusajs/medusa/assets/25098370/5f29b75c-e896-4b44-b5f7-bf0e157ada99">

Then when I put a breakpoint I can see that all functions are available and accessible. for the test, I just wanted to see if the existing function was called, didn't matched the API just for the test purpose 😄 

<img width="1015" alt="Screenshot 2024-01-22 at 10 19 46" src="https://github.com/medusajs/medusa/assets/25098370/671a3ebd-7dde-48bd-80cb-11838665e3c4">

**Comment by vinhnguyen1211** [comment]
Have you tried fetching orders at http://localhost:9000/admin/orders? When I use spread operator I got that error again, I also extend Order service

```typescript
class OrderService extends MedusaOrderService {
  static LIFE_TIME = Lifetime.SCOPED;
  protected readonly loggedInUser_: User | null;

  constructor(container, options) {
    // @ts-expect-error prefer-rest-params
    super(...arguments);

    try {
      this.loggedInUser_ = container.loggedInUser;
    } catch (e) {
      // avoid errors when backend first runs
    }
  }

  async listAndCount(
    selector: QuerySelector<Order> & { store_id?: string },
    config?: FindConfig<Order>,
  ): Promise<[Order[], number]> {
    if (!selector.store_id && this.loggedInUser_?.store_id) {
      selector.store_id = this.loggedInUser_.store_id;
    }

    if (config?.select?.length) {
      config.select.push('store_id');
    }
    if (config?.relations?.length) {
      config.relations.push('store');
    }

    return super.listAndCount(selector, config);
  }
}
```

**Comment by adrien2p** [comment]
Yes, here it is
<img width="1351" alt="Screenshot 2024-01-22 at 10 42 46" src="https://github.com/medusajs/medusa/assets/25098370/31fb4aaf-06ac-4b9b-a28a-97d41d7af861">
<img width="1687" alt="Screenshot 2024-01-22 at 10 42 54" src="https://github.com/medusajs/medusa/assets/25098370/7395fe6e-feba-4647-ab0a-68b06936faed">

**Comment by vinhnguyen1211** [comment]
would you mind also extending OrderService, the important is `return super.listAndCount(selector, config);` will throw error

**Comment by adrien2p** [comment]
sure, give me a sec

**Comment by adrien2p** [comment]
I don't have the store id so I have to comment it but it works
<img width="1713" alt="Screenshot 2024-01-22 at 11 05 22" src="https://github.com/medusajs/medusa/assets/25098370/8d8d7352-5d79-4874-bb9c-b86998f36f90">
<img width="2046" alt="Screenshot 2024-01-22 at 11 05 37" src="https://github.com/medusajs/medusa/assets/25098370/cb81aea0-b2a2-4584-8eec-c524be7bfdb8">

**Comment by vinhnguyen1211** [comment]
Thanks. So I got there're weird issues from my end.
I'll update PR following your suggestion 🙌

**Comment by corentinbranchereau** [comment]
I recently updated  from medusajs/medusa 1.17.2 to medusajs/medusa 1.20.0, and i have the same problem in 1.20.0 where spread operator does not work (it was working in 1.17.2). The suggestion @shahednasser provided seems to fix the problem

> @adrien2p @shahednasser spread operator doesn't work. I just test with your code snippet, it should be like this
> 
> ```ts
> export const OrderRepository = dataSource.getRepository(Order).extend(
>   Object.assign(MedusaOrderRepository, {
>     customFunction(): void {
>       // TODO add custom implementation
>       return
>     }
>   }),
> );
> ```
> 
> seems `{ target: Product }` is redundant

**Comment by kim-hanho** [comment]
Same here as @corentinbranchereau . I updated from old version to 1.20.0, and re-installed node modules.
The only working solution is not using spread operator.

**Comment by raukaute** [comment]
Facing the same issue. Spread operator breaks the functionality. Unfortunately I depend on it in one case, so it broke admin categories completely.

**Comment by ashishbansalmbm** [comment]
Facing the same issue. Spread operator is not working only in the case of Extending Product Entity as in the example.
But working for User and Store Entity.

`error:   productRepo.findWithRelationsAndCount is not a function
TypeError: productRepo.findWithRelationsAndCount is not a function
    at ProductService.<anonymous> (C:\Users\ashis\Desktop\Panda\backend\node_modules\@medusajs\medusa\dist\services\product.js:211:58)
    at step (C:\Users\ashis\Desktop\Panda\backend\node_modules\@medusajs\medusa\dist\services\product.js:59:23)
    at Object.next (C:\Users\ashis\Desktop\Panda\backend\node_modules\@medusajs\medusa\dist\services\product.js:40:53)
    at C:\Users\ashis\Desktop\Panda\backend\node_modules\@medusajs\medusa\dist\services\product.js:34:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\ashis\Desktop\Panda\backend\node_modules\@medusajs\medusa\dist\services\product.js:30:12)
    at ProductService.listAndCount (C:\Users\ashis\Desktop\Panda\backend\node_modules\@medusajs\medusa\dist\services\product.js:189:16)
    at ProductService._callee2$ (C:\Users\ashis\Desktop\Panda\backend\dist\services\product.js:78:126)
    at tryCatch (C:\Users\ashis\Desktop\Panda\backend\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (C:\Users\ashis\Desktop\Panda\backend\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
::1 - - [19/Mar/2024:20:52:08 +0000] "GET /admin/products/ HTTP/1.1" 500 86 "-" "PostmanRuntime/7.37.0"`

**Comment by KabyleBOT** [comment]
I am having the exact same issue with version 1.20.7

**Comment by voronovmaksim** [comment]
v1.20.8 +

`this` works as expected.
`super` is failed with `is not function`

````
import {dataSource,} from "@medusajs/medusa/dist/loaders/database"
import {
    ProductCategoryRepository as MedusaProductCategoryRepository,
} from "@medusajs/medusa/dist/repositories/product-category"
import {ProductCategory} from "../models/product-category";
import {FindManyOptions} from "typeorm";
import {ExtendedFindConfig, QuerySelector} from "@medusajs/medusa";

export const ProductCategoryRepository = dataSource
    .getTreeRepository(ProductCategory) //https://github.com/medusajs/medusa/issues/4461
    .extend({
        ...Object.assign(MedusaProductCategoryRepository),

        async getFreeTextSearchResultsAndCount(
            options: ExtendedFindConfig<ProductCategory> = {
                where: {},
            },
            q?: string,
            treeScope: QuerySelector<ProductCategory> = {},
            includeTree = false
        ): Promise<[ProductCategory[], number]> {
            return super.getFreeTextSearchResultsAndCount(options, q, treeScope, includeTree)
        },

        /**
         * Here you can create your custom function
         * For example
         */
        async retrieveAll(options?: FindManyOptions<ProductCategory>): Promise<ProductCategory[]> {
            return this.find(options)
        },
    })

export default ProductCategoryRepository
````
