### ISSUE TITLE
@medusajs/test-utils@2.16.0 requires "pg-god" but does not declare it (regressed by #15635)

### ISSUE THREAD

**Issue by Ghost1863** [medusajs/medusa#15849]
### System Information

**Package.json**
```json
{
  "dependencies": {
    "@medusajs/test-utils": "2.16.0",
    "@medusajs/medusa": "2.16.0",
    "@medusajs/framework": "2.16.0"
  }
}
```

- **Node.js version:** v20.x
- **Database and its version:** PostgreSQL 16 (not relevant — fails before any DB connection)
- **Operating system:** Linux (Ubuntu 22.04) — environment-independent
- **Browser name:** N/A

### What happened?

`@medusajs/test-utils` calls `require("pg-god")` at runtime but does not list `pg-god` in its `dependencies` (nor peer/optional). It previously worked only because `pg-god` was pulled in transitively by `@medusajs/cli` and hoisted to the root `node_modules`.

#15635 removed `pg-god` from `@medusajs/cli` (replaced with a direct `pg.Pool` call), but `@medusajs/test-utils` was not updated. On a clean install at 2.16.0 nothing provides `pg-god`, and every integration test using `medusaIntegrationTestRunner` fails to even load.

**Evidence (from the published 2.16.0 packages on npm):**

`@medusajs/test-utils@2.16.0` still requires it in code:
```
package/dist/database.js:10  const pg_god_1 = require("pg-god");
package/dist/jest.js:4       const pg_god_1 = require("pg-god");
```

But neither package declares it:
```
$ npm view @medusajs/test-utils@2.16.0 dependencies   # no pg-god
$ npm view @medusajs/cli@2.16.0 dependencies          # no pg-god (removed in #15635)
```

**Error:**
```
Cannot find module 'pg-god' from 'node_modules/@medusajs/test-utils/dist/database.js'
  at Resolver._throwModNotFoundError (node_modules/jest-resolve/build/resolver.js:427:11)
  at Object.<anonymous> (node_modules/@medusajs/test-utils/src/database.ts:10:1)
  at Object.<anonymous> (node_modules/@medusajs/test-utils/src/index.ts:1:1)
```

### Expected behavior

`@medusajs/test-utils` installs and runs without manual intervention. Since its code does `require("pg-god")`, it should declare `pg-god` in its own `dependencies` — or drop the runtime usage the same way #15635 did for the CLI (direct `pg.Pool` create-database call).

### Actual behavior

On a fresh install at 2.16.0, `pg-god` is absent from `node_modules`, so any test using `@medusajs/test-utils` throws "Cannot find module 'pg-god'" at module load — before any test or DB connection runs. This affects all consumers that previously relied on the CLI hoisting `pg-god` to the root.

### Related

Regression introduced by #15635 (removed `pg-god` from `@medusajs/cli`, which was the only transitive provider for `@medusajs/test-utils`).

**Comment by noubase** [comment]
+
